logging:
  level:
    br.com.erpsystem: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_HOST:jdbc:mysql://localhost:3306/db_02_sales_ms}
    username: ${MYSQL_USERNAME:sales-user}
    password: ${MYSQL_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect



