spring:
  flyway:
    enabled: false
    baseline-on-migrate: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

services:
  ms-customer:
    url: http://localhost:8080/api/v1/customer
  ms-products:
    url: http://localhost:8082/api/v1/products
