server:
  port: 8081

spring:
  application:
    name: ms-sales
  rabbitmq:
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    port: ${RABBITMQ_PORT}
    listener:
      simple:
        max-concurrency: 2
    connection-timeout: 1000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

services:
  ms-customer:
    url: http://ms-customer:8080/api/v1/customer
  ms-products:
    url: http://ms-products:8082/api/v1/products


